const VTC_DATA = [
  {
    "id": 1,
    "name": "Kitulu Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Mungoma Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 2,
    "name": "Keveye Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Central Maragoli Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 3,
    "name": "South Maragoli Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "South Maragoli Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 4,
    "name": "Chanzeywe Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Mungoma Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 5,
    "name": "Kegendirova Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Central Maragoli Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 6,
    "name": "Vigetse Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "South Maragoli Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 7,
    "name": "St. Peter's Hambale Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Lugaga Wamuluma Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 8,
    "name": "Busaina Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Lugaga Wamuluma Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 9,
    "name": "Muhanda Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Lugaga Wamuluma Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 10,
    "name": "Lotego Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "Busali Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 11,
    "name": "Mudete Friends Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "Chavakali Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 12,
    "name": "North Maragoli Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "North Maragoli Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 13,
    "name": "Gavudia Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "Wodanga Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 14,
    "name": "Munugi Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "Lyaduywa/Izava Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 15,
    "name": "Solongo Vocational Training Centre",
    "subcounty": "Sabatia",
    "ward": "West Sabatia Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 16,
    "name": "Jepkose Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Gisambai Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 17,
    "name": "Shiru Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Shiru Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 18,
    "name": "Givigoi Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Tambua Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 19,
    "name": "Gimomoi Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Gisambai Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 20,
    "name": "Boyani Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Tambua Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 21,
    "name": "Karandini Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Tambua Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 22,
    "name": "Kaimosi Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Shiru Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 23,
    "name": "Gamande Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Jepkoyai Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 24,
    "name": "Muhudu Vocational Training Centre",
    "subcounty": "Hamisi",
    "ward": "Muhudu Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 25,
    "name": "Nzalwa Vocational Training Centre",
    "subcounty": "Emuhaya",
    "ward": "West Bunyore Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 26,
    "name": "Emmukunzi Vocational Training Centre",
    "subcounty": "Emuhaya",
    "ward": "Central Bunyore Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 27,
    "name": "Mwambeba Vocational Training Centre",
    "subcounty": "Luanda",
    "ward": "Emabungo Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 28,
    "name": "Ebusiralo Vocational Training Centre",
    "subcounty": "Luanda",
    "ward": "Luanda Township Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 29,
    "name": "Ematete Vocational Training Centre",
    "subcounty": "Luanda",
    "ward": "Mwibona Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 30,
    "name": "Maseno Vocational Training Centre",
    "subcounty": "Luanda",
    "ward": "Luanda South Ward",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Verified from Vihiga County directory"
  },
  {
    "id": 31,
    "name": "Ebusiratsi Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Ward/location to confirm",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Registered by TVETA; county placement/profile to confirm"
  },
  {
    "id": 32,
    "name": "Senende Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Ward/location to confirm",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Name reported in county planning material; current status to confirm"
  },
  {
    "id": 33,
    "name": "Shamakhokho Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Ward/location to confirm",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Name reported in county planning material; current status to confirm"
  },
  {
    "id": 34,
    "name": "Kabinjari Vocational Training Centre",
    "subcounty": "Vihiga",
    "ward": "Ward/location to confirm",
    "courses": [],
    "phone": "",
    "email": "",
    "map": "",
    "facebook": "",
    "status": "Name reported in county planning material; current status to confirm"
  }
];
